### ISSUE TITLE
Resilient parsing of HTTP API responses in desktop and mobile clients

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/product#182]
Just learned fro @butonic about the best practise to make parsing API responses as resilient as possible.

For example a **boolean** `true` / `false` or `1` / `0` could also be a **string** `true` / `false` or `1` / `0`

@jesmrec @jnweiger maybe share your specific findings…

@felix-schwarz @hosy @mneuwert @TheOneRing @abelgardep @davigonz FYI

**Comment by butonic** [comment]
see https://en.wikipedia.org/wiki/Robustness_principle

**Comment by felix-schwarz** [comment]
> @jesmrec @jnweiger maybe share your specific findings…

Yeah, please do :)

**Comment by jesmrec** [comment]
First example is here: https://github.com/owncloud/product/issues/181  (oCIS team will fix in that case)

**Comment by jnweiger** [comment]
Looking at the desktop client code:

The desktop client parses strings and integer values as booleans using the toBool() method of Qt: https://doc.qt.io/qt-5/qvariant.html#toBool -- that seems to be a nice implementation of resilient parsing.
The desktop client also expects an "ocs" node around "data" (same problem as pointed out by @jesmrec in #181)
There are more examples, where the desktop client uses toBool, e.g.  "maintenance": "true" 

Looking there, I spotted that https://github.com/owncloud/client/blob/master/src/gui/connectionvalidator.cpp#L306 expects "display-name" instead of "displayname" -- @TheOneRing  that probably never worked correctly?

**Comment by TheOneRing** [comment]
> 
> 
> That is Postel's law: "Be conservative in what you send, be liberal in what you accept"
> 
> Looking at the desktop client code:
> 
> The desktop client parses strings and integer values as booleans using the toBool() method of Qt: https://doc.qt.io/qt-5/qvariant.html#toBool -- that seems to be a nice implementation of resilient/lenient/liberal parsing.
> The desktop client also expects an "ocs" node around "data" (same problem as pointed out by @jesmrec in #181)
> There are more examples, where the desktop client uses toBool, e.g. "maintenance": "true"
> 
> Looking there, I spotted https://github.com/owncloud/client/pull/8044/files -- @TheOneRing that probably never worked correctly?

Yes as long as the server is not returning `False` everything should be fine, https://github.com/owncloud/client/pull/8044/files was approved.
